[package]
name = "app"
version = "1.0.0"
authors = ["Baidu"]
build = "build.rs"

[dependencies]
sgx_types = { path = "../../../sgx_types" }
sgx_urts = { path = "../../../sgx_urts" }
dirs = "1.0.2"
sgx_crypto_helper = { path = "../../../sgx_crypto_helper" }
serde_json = "1.0"
